#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again. This script gets executed directly, so it could be python, php,
# ruby, etc.
# Activate VirtualEnv in order to use the correct libraries

echo "---> ACTION HOOK: deploy <---"
source "$OPENSHIFT_HOMEDIR/python/virtenv/bin/activate"

if [ -f "${OPENSHIFT_DATA_DIR}local_settings.py"]; then
	cp "${OPENSHIFT_DATA_DIR}local_settings.py" "${OPENSHIFT_REPO_DIR}mwach/local_settings.py"
fi

echo "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py collectstatic --noinput'"
python "${OPENSHIFT_REPO_DIR}manage.py" collectstatic --noinput

if [ -z "$OPENSHIFT_KEEP_DB" ]; then
	echo "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py migrate --noinput'"
	python "${OPENSHIFT_REPO_DIR}manage.py" migrate --noinput

	echo "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py reset_db'"
	python "${OPENSHIFT_REPO_DIR}manage.py" reset_db
fi

